### DISCUSSION TITLE
vxe 滚动条计算错误我定位到了位置

### DISCUSSION THREAD

**Discussion by biggerstar** [vbenjs/vue-vben-admin#5771] [Ideas]
![image](https://github.com/user-attachments/assets/afa0bd19-5e20-42fb-a0b9-024b61140f85)

如图， mt-2 取消后就正常了，问题出现在分页器

**Comment by biggerstar** [comment]
暂时使用全局 css 解决
```css
.vxe-grid--pager-wrapper > .vxe-pager {
  margin-top: 0px !important;
}

```
