### ISSUE TITLE
使用最新google浏览器 按钮颜色值不支持！

### ISSUE THREAD

**Issue by fengbindev** [vbenjs/vue-vben-admin#1983]
使用最新google浏览器 按钮颜色值不支持！

google浏览器版本号：版本 86.0.4240.198（正式版本） （32 位）

![image](https://user-images.githubusercontent.com/28595220/174433772-d2e84c3f-6d85-4fca-bbbe-c5d472d1358a.png)

**Comment by Tanimodori** [comment]
《最新》

目前(2022.6.19)的Chrome稳定版是102.0.5005.115，86大概是2020年10月的版本了。官网的演示版是没开`VITE_LEGACY`的，如果需要支持旧版建议自己build的时候加`VITE_LEGACY`试试。

**Comment by Tanimodori** [comment]
查了查caniuse，Chrome对`:not`的支持从88开始，导致以下样式不能工作导致的。

```less
.ant-btn-success:not(.ant-btn-link,.is-disabled) {
    color: #fff;
    background-color: #55d187;
    border-color: #55d187;
}
```
