### ISSUE TITLE
Bug: 项目打包报错

### ISSUE THREAD

**Issue by Guuuxu** [vbenjs/vue-vben-admin#5813]
### Version

Vben Admin V5

### Describe the bug?

![Image](https://github.com/user-attachments/assets/74f120e2-0506-4938-bf9d-283cbe7f9132)

### Reproduction

node: 20.15.0
pnpm: 9.15.0

### System Info

```shell
node: 20.15.0
pnpm: 9.15.0
```

### Relevant log output

```shell
不知为何突然打包不行了 ，我使用nvm切换过版本，之前的项目是没问题的。  使用官方最新demo也是这样，急急急
```

### Validations

- [x] Read the [docs](https://doc.vben.pro/)
- [x] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [x] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jinmao88** [comment]
重新安装依赖试试

**Comment by Guuuxu** [comment]
我发现在根目录可以打包，但是在web-ele/下就不行

**Comment by jxh-0514** [comment]
我也遇到了一样的问题
`
node: 22.7.0
pnpm: 10.6.3
`

![Image](https://github.com/user-attachments/assets/d61a3f6c-a26f-43e7-8798-152c65d92146)

**Comment by Rascal-Coder** [comment]
你这个报错很明显resolve不到某个子包，app中的应用需要依赖大仓中的子包，需要在根目录turbo调度build所有相关依赖

**Comment by jxh-0514** [comment]
> 你这个报错很明显resolve不到某个子包，app中的应用需要依赖大仓中的子包，需要在根目录turbo调度build所有相关依赖

我昨天也试了一下在根目录打包是没问题，在web-ele里就这样报错

**Comment by jxh-0514** [comment]
> > 你这个报错很明显resolve不到某个子包，app中的应用需要依赖大仓中的子包，需要在根目录turbo调度build所有相关依赖
> 
> 我昨天也试了一下在根目录打包是没问题，在web-ele里就这样报错

我刚把node升级到22.9.0  在web-ele下打包就没问题了

**Comment by jxh-0514** [comment]
> > > 你这个报错很明显resolve不到某个子包，app中的应用需要依赖大仓中的子包，需要在根目录turbo调度build所有相关依赖
> > 
> > 
> > 我昨天也试了一下在根目录打包是没问题，在web-ele里就这样报错
> 
> 我刚把node升级到22.9.0 在web-ele下打包就没问题了

我本地打包已经没问题了，但是构建的报错和题主的一样
```yaml
name: CI Github Pages

on:
  push:
    branches:
      - dev  # 监听dev分支的push操作

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'  # 指定所需的 Node.js 版本

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install and Build
        run: |
          pnpm install
          cd apps/web-ele
          pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages  # 部署后提交到新的分支
          folder: apps/web-ele/dist  # 打包后的目录路径
          token: ${{ secrets.GITHUB_TOKEN }}

```
